### ISSUE TITLE
[Feature Request] Provide a C API for FFI support in other programming languages

### ISSUE THREAD

**Issue by PureTryOut** [MayaPosch/libnymphcast#1]
I'm trying to generate bindings for this library for a different language, in my case Dart, through FFI. However FFI only works with C API's and thus the generator can't parse `nymphcast_client.h`. It would be great if a C API could be provided so clients can be written in way more languages than just C++.

**Comment by PureTryOut** [comment]
Hey @MayaPosch, any opinions about this? I'd love to write both a control client in Flutter and add support for Nymphcast to [Spotube](https://github.com/KRTirtho/spotube), both of which would need a C API for this library to be available :sweat_smile: 

I can also imagine people using Python bindings which would also need a C API for FFI, and I'm sure there are more usable languages out there that use FFI.

**Comment by MayaPosch** [comment]
I'm not entirely sure what FFI is, but a C API is definitely a good idea. I can't give a definite timeline for when it may be done, but I'll keep this ticket updated with progress :)

**Comment by PureTryOut** [comment]
"Foreign function interface", basically a way to call methods and functions in alternative languages. It really only works with C though since it's by far the most compatible, so often programs written in other languages provide a C interface for such things.

**Comment by MayaPosch** [comment]
I have added an initial C binding (targeting C11) along with an example application. 

It's still untested, but it does compile and link :)

Next step is to test it out and debug any remaining issues, add documentation to the project's README and that should be all. Feel free to give this early draft a try as well. It relies on the two files in the `binding/c/` folder, with the header providing the C interface, and the CPP file the bridge between C & C++.

**Comment by MayaPosch** [comment]
I tested the C bindings example application today, and it's able to successfully fetch the list of NCS and NCMS instances on the network here, along with the files shared by each NCMS. Will unleash Valgrind on the thing as well at some point to be sure, but pretty certain it should be ready for general usage at least :)

I updated the README with basic instructions on how to use the C binding. Please have a look and see whether there's anything more that you'd need to use the binding for your purposes.

**Comment by MayaPosch** [comment]
Closing as completed. Please open a new ticket if any issues are found.
